name: my_flutter_app
description: A Flutter application with image galleries and custom transitions.
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^5.2.1
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/Anu/image1.png
    - assets/Anu/image2.jpg
    - assets/Anu/image3.jpg
    - assets/Ashish/image4.jpg
    - assets/Ashish/image5.jpg
    - assets/Ashish/image6.jpg
    - assets/Us/image7.png
    - assets/Us/image8.jpg
    - assets/Us/image9.jpg
    - assets/Us/image10.jpg
    - assets/Us/image11.jpg
    - assets/Us/image12.jpg
    - assets/Us/image13.jpg
    - assets/Us/image14.jpg
    - assets/Us/image15.jpg
    - assets/icon/app_icon.png
    - assets/music/audio.mp3

