# Language: YAML
name: Deploy to Firebase Hosting on PR
on: pull_request
permissions:
  checks: write
  contents: write
  pull-requests: write
jobs:
  build_and_preview:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.5'
      - name: clean up
        run: flutter clean
      - name: Install Dependencies
        run: flutter pub get
      - name: Build Web App
        run: flutter build web --release
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BUG_BUG_24D90 }}
          projectId: bug-bug-24d90